config/routes.rb
Rails.application.routes.draw do
  root to: 'root#index'
  resources :urls, only: %i[index new create show] do
    member do
      get 'stats'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :short_hash, presence: true, uniqueness: true
  validates :url, presence: true

  def self.generate_code(length=5)
    symbols = [('a'..'z'), ('A'..'Z'), (1..9)].map(&:to_a).flatten
    (0...length).map { symbols[rand(symbols.length)] }.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
  end

  def new
  end

  def create
    begin
      retries ||= 0

      code = Url.generate_code
      @url = Url.create(url: params[:url], short_hash: code)
    rescue
      retry if (retries += 1) < 3
    end
  end

  def show
    record = Url.find_by_short_hash(params[:id])
    raise ActionController::RoutingError.new('Not Found') if record.blank?

    record.increment!(:views_count)

    redirect_to(record.url)
  end

  def stats
    @url = Url.find_by_short_hash(params[:id])
    raise ActionController::RoutingError.new('Not Found') if @url.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShorter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_url_form.html.erb
<form action="<%= urls_path %>" method="post">
  URL:
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" value="" name="url" />
  <input type="submit" value="Добавить" />
</form>

app/views/root/index.html.erb
<h1>Добавить url</h1>
<%= render partial: 'partials/url_form' %>

app/views/urls/create.html.erb
<h1>Url</h1>
<% if @url.errors.present? %>
  <% @url.errors.messages.each do |k, v| %>
    <%= k %> <%= v %>
  <% end %>
<% else %>
Ваш url: <a href="http://<%= request.host_with_port %><%= url_path(@url.short_hash) %>" target="_blank">http://<%= request.host_with_port %><%= url_path(@url.short_hash) %></a>
<br />
<br />
<a href="http://<%= request.host_with_port %><%= stats_url_path(@url.short_hash) %>" target="_blank">Статистика</a>
<% end %>

app/views/urls/index.html.erb
<h1>Добавить url</h1>
<%= render partial: 'partials/url_form' %>

app/views/urls/new.html.erb
<h1>Добавить url</h1>
<%= render partial: 'partials/url_form' %>

app/views/urls/stats.html.erb
<h1>Количество переходов</h1>
<%= @url.views_count %>